export const GET_EXTERNAL_CONTACTS_START =
  'GET_EXTERNAL_CONTACTS_START';
export const GET_EXTERNAL_CONTACTS_SUCCESS =
  'GET_EXTERNAL_CONTACTS_SUCCESS';
export const GET_EXTERNAL_CONTACTS_ERROR =
  'GET_EXTERNAL_CONTACTS_ERROR';
export const GET_EXTERNAL_CONTACTS_END = 'GET_EXTERNAL_CONTACTS_END';
export const GET_EXTERNAL_CONTACTS_CLEAR =
  'GET_EXTERNAL_CONTACTS_CLEAR';
