export const GET_INTERNAL_CONTACTS_START =
  'GET_INTERNAL_CONTACTS_START';
export const GET_INTERNAL_CONTACTS_SUCCESS =
  'GET_INTERNAL_CONTACTS_SUCCESS';
export const GET_INTERNAL_CONTACTS_ERROR =
  'GET_INTERNAL_CONTACTS_ERROR';
export const GET_INTERNAL_CONTACTS_END = 'GET_INTERNAL_CONTACTS_END';
export const GET_INTERNAL_CONTACTS_CLEAR =
  'GET_INTERNAL_CONTACTS_CLEAR';
