export const GET_DEFAULT_WALLET_START = 'GET_DEFAULT_WALLET_START';
export const GET_DEFAULT_WALLET_SUCCESS =
  'GET_DEFAULT_WALLET_SUCCESS';
export const GET_DEFAULT_WALLET_ERROR = 'GET_DEFAULT_WALLET_ERROR';
export const GET_DEFAULT_WALLET_END = 'GET_DEFAULT_WALLET_END';
