export const CANCEL_TRANSACTION_START = 'CANCEL_TRANSACTION_START';
export const CANCEL_TRANSACTION_ERROR = 'CANCEL_TRANSACTION_ERROR';
export const CANCEL_TRANSACTION_SUCCESS =
  'CANCEL_TRANSACTION_SUCCESS';
