export const GET_RECENT_ACTIVE_CONTACTS_ERROR =
  'GET_RECENT_ACTIVE_CONTACTS_ERROR';
export const GET_RECENT_ACTIVE_CONTACTS_SUCCESS =
  'GET_RECENT_ACTIVE_CONTACTS_SUCCESS';
export const GET_RECENT_ACTIVE_CONTACTS_START =
  'GET_RECENT_ACTIVE_CONTACTS_START';
