export const GET_CONTACT_LIST_START = 'GET_CONTACT_LIST_START';
export const GET_CONTACT_LIST_SUCCESS = 'GET_CONTACT_LIST_SUCCESS';
export const GET_CONTACT_LIST_ERROR = 'GET_CONTACT_LIST_ERROR';
export const ADD_NEW_CONTACT_ERROR = 'ADD_NEW_CONTACT_ERROR';
export const ADD_NEW_CONTACT_SUCCESS = 'ADD_NEW_CONTACT_SUCCESS';
export const ADD_NEW_CONTACT_START = 'ADD_NEW_CONTACT_START';
export const ADD_EXTERNAL_CONTACT_ERROR =
  'ADD_EXTERNAL_CONTACT_ERROR';
export const ADD_EXTERNAL_CONTACT_SUCCESS =
  'ADD_EXTERNAL_CONTACT_SUCCESS';
export const ADD_EXTERNAL_CONTACT_START =
  'ADD_EXTERNAL_CONTACT_START';
export const GET_EXTERNAL_CONTACT_LIST_START =
  'GET_EXTERNAL_CONTACT_LIST_START';
export const GET_EXTERNAL_CONTACT_LIST_SUCCESS =
  'GET_EXTERNAL_CONTACT_LIST_SUCCESS';
export const GET_EXTERNAL_CONTACT_LIST_ERROR =
  'GET_EXTERNAL_CONTACT_LIST_ERROR';
