export const SAVE_BANK_ACCOUNT_START = 'SAVE_BANK_ACCOUNT_START';
export const SAVE_BANK_ACCOUNT_SUCCESS = 'SAVE_BANK_ACCOUNT_SUCCESS';
export const SAVE_BANK_ACCOUNT_ERROR = 'SAVE_BANK_ACCOUNT_ERROR';
export const CLEAR_SAVE_BANK_ACCOUNT_STORE =
  'CLEAR_SAVE_BANK_ACCOUNT_STORE';
