export default [
  {
    text: 'Afghanistan',
    value: 'Afghanistan',
    flag: 'af',
    key: 'af',
  },
  {
    text: 'Aland Islands',
    value: 'Aland Islands',
    flag: 'ax',
    key: 'ax',
  },
  { text: 'Albania', value: 'Albania', flag: 'al', key: 'al' },
  { text: 'Algeria', value: 'Algeria', flag: 'dz', key: 'dz' },
  {
    text: 'American Samoa',
    value: 'American Samoa',
    flag: 'as',
    key: 'as',
  },
  { text: 'Andorra', value: 'Andorra', flag: 'ad', key: 'ad' },
  { text: 'Angola', value: 'Angola', flag: 'ao', key: 'ao' },
  { text: 'Anguilla', value: 'Anguilla', flag: 'ai', key: 'ai' },
  { text: 'Antigua', value: 'Antigua', flag: 'ag', key: 'ag' },
  { text: 'Argentina', value: 'Argentina', flag: 'ar', key: 'ar' },
  { text: 'Armenia', value: 'Armenia', flag: 'am', key: 'am' },
  { text: 'Aruba', value: 'Aruba', flag: 'aw', key: 'aw' },
  { text: 'Australia', value: 'Australia', flag: 'au', key: 'au' },
  { text: 'Austria', value: 'Austria', flag: 'at', key: 'at' },
  { text: 'Azerbaijan', value: 'Azerbaijan', flag: 'az', key: 'az' },
  { text: 'Bahamas', value: 'Bahamas', flag: 'bs', key: 'bs' },
  { text: 'Bahrain', value: 'Bahrain', flag: 'bh', key: 'bh' },
  { text: 'Bangladesh', value: 'Bangladesh', flag: 'bd', key: 'bd' },
  { text: 'Barbados', value: 'Barbados', flag: 'bb', key: 'bb' },
  { text: 'Belarus', value: 'Belarus', flag: 'by', key: 'by' },
  { text: 'Belgium', value: 'Belgium', flag: 'be', key: 'be' },
  { text: 'Belize', value: 'Belize', flag: 'bz', key: 'bz' },
  { text: 'Benin', value: 'Benin', flag: 'bj', key: 'bj' },
  { text: 'Bermuda', value: 'Bermuda', flag: 'bm', key: 'bm' },
  { text: 'Bhutan', value: 'Bhutan', flag: 'bt', key: 'bt' },
  { text: 'Bolivia', value: 'Bolivia', flag: 'bo', key: 'bo' },
  { text: 'Bosnia', value: 'Bosnia', flag: 'ba', key: 'ba' },
  { text: 'Botswana', value: 'Botswana', flag: 'bw', key: 'bw' },
  {
    text: 'Bouvet Island',
    value: 'Bouvet Island',
    flag: 'bv',
    key: 'bv',
  },
  { text: 'Brazil', value: 'Brazil', flag: 'br', key: 'br' },
  {
    text: 'British Virgin Islands',
    value: 'British Virgin Islands',
    flag: 'vg',
    key: 'vg',
  },
  { text: 'Brunei', value: 'Brunei', flag: 'bn', key: 'bn' },
  { text: 'Bulgaria', value: 'Bulgaria', flag: 'bg', key: 'bg' },
  {
    text: 'Burkina Faso',
    value: 'Burkina Faso',
    flag: 'bf',
    key: 'bf',
  },
  { text: 'Burma', value: 'Burma', flag: 'mm', key: 'mm' },
  { text: 'Burundi', value: 'Burundi', flag: 'bi', key: 'bi' },
  {
    text: 'Caicos Islands',
    value: 'Caicos Islands',
    flag: 'tc',
    key: 'tc',
  },
  { text: 'Cambodia', value: 'Cambodia', flag: 'kh', key: 'kh' },
  { text: 'Cameroon', value: 'Cameroon', flag: 'cm', key: 'cm' },
  { text: 'Canada', value: 'Canada', flag: 'ca', key: 'ca' },
  { text: 'Cape Verde', value: 'Cape Verde', flag: 'cv', key: 'cv' },
  {
    text: 'Cayman Islands',
    value: 'Cayman Islands',
    flag: 'ky',
    key: 'ky',
  },
  {
    text: 'Central African Republic',
    value: 'Central African Republic',
    flag: 'cf',
    key: 'cf',
  },
  { text: 'Chad', value: 'Chad', flag: 'td', key: 'td' },
  { text: 'Chile', value: 'Chile', flag: 'cl', key: 'cl' },
  { text: 'China', value: 'China', flag: 'cn', key: 'cn' },
  {
    text: 'Christmas Island',
    value: 'Christmas Island',
    flag: 'cx',
    key: 'cx',
  },
  {
    text: 'Cocos Islands',
    value: 'Cocos Islands',
    flag: 'cc',
    key: 'cc',
  },
  { text: 'Colombia', value: 'Colombia', flag: 'co', key: 'co' },
  { text: 'Comoros', value: 'Comoros', flag: 'km', key: 'km' },
  { text: 'Congo', value: 'Congo', flag: 'cd', key: 'cd' },
  {
    text: 'Congo Brazzaville',
    value: 'Congo Brazzaville',
    flag: 'cg',
    key: 'cg',
  },
  {
    text: 'Cook Islands',
    value: 'Cook Islands',
    flag: 'ck',
    key: 'ck',
  },
  { text: 'Costa Rica', value: 'Costa Rica', flag: 'cr', key: 'cr' },
  {
    text: 'Cote Divoire',
    value: 'Cote Divoire',
    flag: 'ci',
    key: 'ci',
  },
  { text: 'Croatia', value: 'Croatia', flag: 'hr', key: 'hr' },
  { text: 'Cuba', value: 'Cuba', flag: 'cu', key: 'cu' },
  { text: 'Cyprus', value: 'Cyprus', flag: 'cy', key: 'cy' },
  {
    text: 'Czech Republic',
    value: 'Czech Republic',
    flag: 'cz',
    key: 'cz',
  },
  { text: 'Denmark', value: 'Denmark', flag: 'dk', key: 'dk' },
  { text: 'Djibouti', value: 'Djibouti', flag: 'dj', key: 'dj' },
  { text: 'Dominica', value: 'Dominica', flag: 'dm', key: 'dm' },
  {
    text: 'Dominican Republic',
    value: 'Dominican Republic',
    flag: 'do',
    key: 'do',
  },
  { text: 'Ecuador', value: 'Ecuador', flag: 'ec', key: 'ec' },
  { text: 'Egypt', value: 'Egypt', flag: 'eg', key: 'eg' },
  {
    text: 'El Salvador',
    value: 'El Salvador',
    flag: 'sv',
    key: 'sv',
  },
  {
    text: 'Equatorial Guinea',
    value: 'Equatorial Guinea',
    flag: 'gq',
    key: 'gq',
  },
  { text: 'Eritrea', value: 'Eritrea', flag: 'er', key: 'er' },
  { text: 'Estonia', value: 'Estonia', flag: 'ee', key: 'ee' },
  { text: 'Ethiopia', value: 'Ethiopia', flag: 'et', key: 'et' },
  {
    text: 'Europeanunion',
    value: 'Europeanunion',
    flag: 'eu',
    key: 'eu',
  },
  {
    text: 'Falkland Islands',
    value: 'Falkland Islands',
    flag: 'fk',
    key: 'fk',
  },
  {
    text: 'Faroe Islands',
    value: 'Faroe Islands',
    flag: 'fo',
    key: 'fo',
  },
  { text: 'Fiji', value: 'Fiji', flag: 'fj', key: 'fj' },
  { text: 'Finland', value: 'Finland', flag: 'fi', key: 'fi' },
  { text: 'France', value: 'France', flag: 'fr', key: 'fr' },
  {
    text: 'French Guiana',
    value: 'French Guiana',
    flag: 'gf',
    key: 'gf',
  },
  {
    text: 'French Polynesia',
    value: 'French Polynesia',
    flag: 'pf',
    key: 'pf',
  },
  {
    text: 'French Territories',
    value: 'French Territories',
    flag: 'tf',
    key: 'tf',
  },
  { text: 'Gabon', value: 'Gabon', flag: 'ga', key: 'ga' },
  { text: 'Gambia', value: 'Gambia', flag: 'gm', key: 'gm' },
  { text: 'Georgia', value: 'Georgia', flag: 'ge', key: 'ge' },
  { text: 'Germany', value: 'Germany', flag: 'de', key: 'de' },
  { text: 'Ghana', value: 'Ghana', flag: 'gh', key: 'gh' },
  { text: 'Gibraltar', value: 'Gibraltar', flag: 'gi', key: 'gi' },
  { text: 'Greece', value: 'Greece', flag: 'gr', key: 'gr' },
  { text: 'Greenland', value: 'Greenland', flag: 'gl', key: 'gl' },
  { text: 'Grenada', value: 'Grenada', flag: 'gd', key: 'gd' },
  { text: 'Guadeloupe', value: 'Guadeloupe', flag: 'gp', key: 'gp' },
  { text: 'Guam', value: 'Guam', flag: 'gu', key: 'gu' },
  { text: 'Guatemala', value: 'Guatemala', flag: 'gt', key: 'gt' },
  { text: 'Guinea', value: 'Guinea', flag: 'gn', key: 'gn' },
  {
    text: 'Guinea-Bissau',
    value: 'Guinea-Bissau',
    flag: 'gw',
    key: 'gw',
  },
  { text: 'Guyana', value: 'Guyana', flag: 'gy', key: 'gy' },
  { text: 'Haiti', value: 'Haiti', flag: 'ht', key: 'ht' },
  {
    text: 'Heard Island',
    value: 'Heard Island',
    flag: 'hm',
    key: 'hm',
  },
  { text: 'Honduras', value: 'Honduras', flag: 'hn', key: 'hn' },
  { text: 'Hong Kong', value: 'Hong Kong', flag: 'hk', key: 'hk' },
  { text: 'Hungary', value: 'Hungary', flag: 'hu', key: 'hu' },
  { text: 'Iceland', value: 'Iceland', flag: 'is', key: 'is' },
  { text: 'India', value: 'India', flag: 'in', key: 'in' },
  {
    text: 'Indian Ocean Territory',
    value: 'Indian Ocean Territory',
    flag: 'io',
    key: 'io',
  },
  { text: 'Indonesia', value: 'Indonesia', flag: 'id', key: 'id' },
  { text: 'Iran', value: 'Iran', flag: 'ir', key: 'ir' },
  { text: 'Iraq', value: 'Iraq', flag: 'iq', key: 'iq' },
  { text: 'Ireland', value: 'Ireland', flag: 'ie', key: 'ie' },
  { text: 'Israel', value: 'Israel', flag: 'il', key: 'il' },
  { text: 'Italy', value: 'Italy', flag: 'it', key: 'it' },
  { text: 'Jamaica', value: 'Jamaica', flag: 'jm', key: 'jm' },
  { text: 'Jan Mayen', value: 'Jan Mayen', flag: 'sj', key: 'sj' },
  { text: 'Japan', value: 'Japan', flag: 'jp', key: 'jp' },
  { text: 'Jordan', value: 'Jordan', flag: 'jo', key: 'jo' },
  { text: 'Kazakhstan', value: 'Kazakhstan', flag: 'kz', key: 'kz' },
  { text: 'Kenya', value: 'Kenya', flag: 'ke', key: 'ke' },
  { text: 'Kiribati', value: 'Kiribati', flag: 'ki', key: 'ki' },
  { text: 'Kuwait', value: 'Kuwait', flag: 'kw', key: 'kw' },
  { text: 'Kyrgyzstan', value: 'Kyrgyzstan', flag: 'kg', key: 'kg' },
  { text: 'Laos', value: 'Laos', flag: 'la', key: 'la' },
  { text: 'Latvia', value: 'Latvia', flag: 'lv', key: 'lv' },
  { text: 'Lebanon', value: 'Lebanon', flag: 'lb', key: 'lb' },
  { text: 'Lesotho', value: 'Lesotho', flag: 'ls', key: 'ls' },
  { text: 'Liberia', value: 'Liberia', flag: 'lr', key: 'lr' },
  { text: 'Libya', value: 'Libya', flag: 'ly', key: 'ly' },
  {
    text: 'Liechtenstein',
    value: 'Liechtenstein',
    flag: 'li',
    key: 'li',
  },
  { text: 'Lithuania', value: 'Lithuania', flag: 'lt', key: 'lt' },
  { text: 'Luxembourg', value: 'Luxembourg', flag: 'lu', key: 'lu' },
  { text: 'Macau', value: 'Macau', flag: 'mo', key: 'mo' },
  { text: 'Macedonia', value: 'Macedonia', flag: 'mk', key: 'mk' },
  { text: 'Madagascar', value: 'Madagascar', flag: 'mg', key: 'mg' },
  { text: 'Malawi', value: 'Malawi', flag: 'mw', key: 'mw' },
  { text: 'Malaysia', value: 'Malaysia', flag: 'my', key: 'my' },
  { text: 'Maldives', value: 'Maldives', flag: 'mv', key: 'mv' },
  { text: 'Mali', value: 'Mali', flag: 'ml', key: 'ml' },
  { text: 'Malta', value: 'Malta', flag: 'mt', key: 'mt' },
  {
    text: 'Marshall Islands',
    value: 'Marshall Islands',
    flag: 'mh',
    key: 'mh',
  },
  { text: 'Martinique', value: 'Martinique', flag: 'mq', key: 'mq' },
  { text: 'Mauritania', value: 'Mauritania', flag: 'mr', key: 'mr' },
  { text: 'Mauritius', value: 'Mauritius', flag: 'mu', key: 'mu' },
  { text: 'Mayotte', value: 'Mayotte', flag: 'yt', key: 'yt' },
  { text: 'Mexico', value: 'Mexico', flag: 'mx', key: 'mx' },
  { text: 'Micronesia', value: 'Micronesia', flag: 'fm', key: 'fm' },
  { text: 'Moldova', value: 'Moldova', flag: 'md', key: 'md' },
  { text: 'Monaco', value: 'Monaco', flag: 'mc', key: 'mc' },
  { text: 'Mongolia', value: 'Mongolia', flag: 'mn', key: 'mn' },
  { text: 'Montenegro', value: 'Montenegro', flag: 'me', key: 'me' },
  { text: 'Montserrat', value: 'Montserrat', flag: 'ms', key: 'ms' },
  { text: 'Morocco', value: 'Morocco', flag: 'ma', key: 'ma' },
  { text: 'Mozambique', value: 'Mozambique', flag: 'mz', key: 'mz' },
  { text: 'Namibia', value: 'Namibia', flag: 'na', key: 'na' },
  { text: 'Nauru', value: 'Nauru', flag: 'nr', key: 'nr' },
  { text: 'Nepal', value: 'Nepal', flag: 'np', key: 'np' },
  {
    text: 'Netherlands',
    value: 'Netherlands',
    flag: 'nl',
    key: 'nl',
  },
  {
    text: 'Netherlandsantilles',
    value: 'Netherlandsantilles',
    flag: 'an',
    key: 'an',
  },
  {
    text: 'New Caledonia',
    value: 'New Caledonia',
    flag: 'nc',
    key: 'nc',
  },
  { text: 'New Guinea', value: 'New Guinea', flag: 'pg', key: 'pg' },
  {
    text: 'New Zealand',
    value: 'New Zealand',
    flag: 'nz',
    key: 'nz',
  },
  { text: 'Nicaragua', value: 'Nicaragua', flag: 'ni', key: 'ni' },
  { text: 'Niger', value: 'Niger', flag: 'ne', key: 'ne' },
  { text: 'Nigeria', value: 'Nigeria', flag: 'ng', key: 'ng' },
  { text: 'Niue', value: 'Niue', flag: 'nu', key: 'nu' },
  {
    text: 'Norfolk Island',
    value: 'Norfolk Island',
    flag: 'nf',
    key: 'nf',
  },
  {
    text: 'North Korea',
    value: 'North Korea',
    flag: 'kp',
    key: 'kp',
  },
  {
    text: 'Northern Mariana Islands',
    value: 'Northern Mariana Islands',
    flag: 'mp',
    key: 'mp',
  },
  { text: 'Norway', value: 'Norway', flag: 'no', key: 'no' },
  { text: 'Oman', value: 'Oman', flag: 'om', key: 'om' },
  { text: 'Pakistan', value: 'Pakistan', flag: 'pk', key: 'pk' },
  { text: 'Palau', value: 'Palau', flag: 'pw', key: 'pw' },
  { text: 'Palestine', value: 'Palestine', flag: 'ps', key: 'ps' },
  { text: 'Panama', value: 'Panama', flag: 'pa', key: 'pa' },
  { text: 'Paraguay', value: 'Paraguay', flag: 'py', key: 'py' },
  { text: 'Peru', value: 'Peru', flag: 'pe', key: 'pe' },
  {
    text: 'Philippines',
    value: 'Philippines',
    flag: 'ph',
    key: 'ph',
  },
  {
    text: 'Pitcairn Islands',
    value: 'Pitcairn Islands',
    flag: 'pn',
    key: 'pn',
  },
  { text: 'Poland', value: 'Poland', flag: 'pl', key: 'pl' },
  { text: 'Portugal', value: 'Portugal', flag: 'pt', key: 'pt' },
  {
    text: 'Puerto Rico',
    value: 'Puerto Rico',
    flag: 'pr',
    key: 'pr',
  },
  { text: 'Qatar', value: 'Qatar', flag: 'qa', key: 'qa' },
  { text: 'Reunion', value: 'Reunion', flag: 're', key: 're' },
  { text: 'Romania', value: 'Romania', flag: 'ro', key: 'ro' },
  { text: 'Russia', value: 'Russia', flag: 'ru', key: 'ru' },
  { text: 'Rwanda', value: 'Rwanda', flag: 'rw', key: 'rw' },
  {
    text: 'Saint Helena',
    value: 'Saint Helena',
    flag: 'sh',
    key: 'sh',
  },
  {
    text: 'Saint Kitts and Nevis',
    value: 'Saint Kitts and Nevis',
    flag: 'kn',
    key: 'kn',
  },
  {
    text: 'Saint Lucia',
    value: 'Saint Lucia',
    flag: 'lc',
    key: 'lc',
  },
  {
    text: 'Saint Pierre',
    value: 'Saint Pierre',
    flag: 'pm',
    key: 'pm',
  },
  {
    text: 'Saint Vincent',
    value: 'Saint Vincent',
    flag: 'vc',
    key: 'vc',
  },
  { text: 'Samoa', value: 'Samoa', flag: 'ws', key: 'ws' },
  { text: 'San Marino', value: 'San Marino', flag: 'sm', key: 'sm' },
  {
    text: 'Sandwich Islands',
    value: 'Sandwich Islands',
    flag: 'gs',
    key: 'gs',
  },
  { text: 'Sao Tome', value: 'Sao Tome', flag: 'st', key: 'st' },
  {
    text: 'Saudi Arabia',
    value: 'Saudi Arabia',
    flag: 'sa',
    key: 'sa',
  },
  {
    text: 'Scotland',
    value: 'Scotland',
    flag: 'gb sct',
    key: 'gb sct',
  },
  { text: 'Senegal', value: 'Senegal', flag: 'sn', key: 'sn' },
  { text: 'Serbia', value: 'Serbia', flag: 'rs', key: 'rs' },
  { text: 'Seychelles', value: 'Seychelles', flag: 'sc', key: 'sc' },
  {
    text: 'Sierra Leone',
    value: 'Sierra Leone',
    flag: 'sl',
    key: 'sl',
  },
  { text: 'Singapore', value: 'Singapore', flag: 'sg', key: 'sg' },
  { text: 'Slovakia', value: 'Slovakia', flag: 'sk', key: 'sk' },
  { text: 'Slovenia', value: 'Slovenia', flag: 'si', key: 'si' },
  {
    text: 'Solomon Islands',
    value: 'Solomon Islands',
    flag: 'sb',
    key: 'sb',
  },
  { text: 'Somalia', value: 'Somalia', flag: 'so', key: 'so' },
  {
    text: 'South Africa',
    value: 'South Africa',
    flag: 'za',
    key: 'za',
  },
  {
    text: 'South Korea',
    value: 'South Korea',
    flag: 'kr',
    key: 'kr',
  },
  { text: 'Spain', value: 'Spain', flag: 'es', key: 'es' },
  { text: 'Sri Lanka', value: 'Sri Lanka', flag: 'lk', key: 'lk' },
  { text: 'Sudan', value: 'Sudan', flag: 'sd', key: 'sd' },
  { text: 'Suriname', value: 'Suriname', flag: 'sr', key: 'sr' },
  { text: 'Swaziland', value: 'Swaziland', flag: 'sz', key: 'sz' },
  { text: 'Sweden', value: 'Sweden', flag: 'se', key: 'se' },
  {
    text: 'Switzerland',
    value: 'Switzerland',
    flag: 'ch',
    key: 'ch',
  },
  { text: 'Syria', value: 'Syria', flag: 'sy', key: 'sy' },
  { text: 'Taiwan', value: 'Taiwan', flag: 'tw', key: 'tw' },
  { text: 'Tajikistan', value: 'Tajikistan', flag: 'tj', key: 'tj' },
  { text: 'Tanzania', value: 'Tanzania', flag: 'tz', key: 'tz' },
  { text: 'Thailand', value: 'Thailand', flag: 'th', key: 'th' },
  { text: 'Timorleste', value: 'Timorleste', flag: 'tl', key: 'tl' },
  { text: 'Togo', value: 'Togo', flag: 'tg', key: 'tg' },
  { text: 'Tokelau', value: 'Tokelau', flag: 'tk', key: 'tk' },
  { text: 'Tonga', value: 'Tonga', flag: 'to', key: 'to' },
  { text: 'Trinidad', value: 'Trinidad', flag: 'tt', key: 'tt' },
  { text: 'Tunisia', value: 'Tunisia', flag: 'tn', key: 'tn' },
  { text: 'Turkey', value: 'Turkey', flag: 'tr', key: 'tr' },
  {
    text: 'Turkmenistan',
    value: 'Turkmenistan',
    flag: 'tm',
    key: 'tm',
  },
  { text: 'Tuvalu', value: 'Tuvalu', flag: 'tv', key: 'tv' },
  {
    text: 'United Arab Emirates',
    value: 'United Arab Emirates',
    flag: 'ae',
    key: 'ae',
  },
  { text: 'Uganda', value: 'Uganda', flag: 'ug', key: 'ug' },
  { text: 'Ukraine', value: 'Ukraine', flag: 'ua', key: 'ua' },
  {
    text: 'United Kingdom',
    value: 'United Kingdom',
    flag: 'gb',
    key: 'gb',
  },
  {
    text: 'United States',
    value: 'United States',
    flag: 'us',
    key: 'us',
  },
  { text: 'Uruguay', value: 'Uruguay', flag: 'uy', key: 'uy' },
  {
    text: 'US Minor Islands',
    value: 'US Minor Islands',
    flag: 'um',
    key: 'um',
  },
  {
    text: 'US Virgin Islands',
    value: 'US Virgin Islands',
    flag: 'vi',
    key: 'vi',
  },
  { text: 'Uzbekistan', value: 'Uzbekistan', flag: 'uz', key: 'uz' },
  { text: 'Vanuatu', value: 'Vanuatu', flag: 'vu', key: 'vu' },
  {
    text: 'Vatican City',
    value: 'Vatican City',
    flag: 'va',
    key: 'va',
  },
  { text: 'Venezuela', value: 'Venezuela', flag: 've', key: 've' },
  { text: 'Vietnam', value: 'Vietnam', flag: 'vn', key: 'vn' },
  { text: 'Wales', value: 'Wales', flag: 'gb wls', key: 'gb wls' },
  {
    text: 'Wallis and Futuna',
    value: 'Wallis and Futuna',
    flag: 'wf',
    key: 'wf',
  },
  {
    text: 'Western Sahara',
    value: 'Western Sahara',
    flag: 'eh',
    key: 'eh',
  },
  { text: 'Yemen', value: 'Yemen', flag: 'ye', key: 'ye' },
  { text: 'Zambia', value: 'Zambia', flag: 'zm', key: 'zm' },
  { text: 'Zimbabwe', value: 'Zimbabwe', flag: 'zw', key: 'zw' },
];
