export const CONFIRM_TRANSACTION_ERROR = 'CONFIRM_TRANSACTION_ERROR';
export const CONFIRM_TRANSACTION_SUCCESS =
  'CONFIRM_TRANSACTION_SUCCESS';
export const CONFIRM_TRANSACTION_START = 'CONFIRM_TRANSACTION_START';
export const MOVE_FUNDS_ERROR = 'MOVE_FUNDS_ERROR';
export const MOVE_FUNDS_SUCCESS = 'MOVE_FUNDS_SUCCESS';
export const MOVE_FUNDS_START = 'MOVE_FUNDS_START';
export const CLEAR_TRANSACTION_INFO = 'CLEAR_TRANSACTION_INFO';
export const CLEAR_MOVE_FUNDS_ERRORS = 'CLEAR_MOVE_FUNDS_ERRORS';
