export const CONFIRM_TRANSACTION_ERROR = 'CONFIRM_TRANSACTION_ERROR';
export const CONFIRM_TRANSACTION_SUCCESS =
  'CONFIRM_TRANSACTION_SUCCESS';
export const CONFIRM_TRANSACTION_START = 'CONFIRM_TRANSACTION_START';
export const MOVE_FUNDS_ERROR = 'MOVE_FUNDS_ERROR';
export const MOVE_FUNDS_SUCCESS = 'MOVE_FUNDS_SUCCESS';
export const MOVE_FUNDS_START = 'MOVE_FUNDS_START';
export const CLEAR_TRANSACTION_INFO = 'CLEAR_TRANSACTION_INFO';
export const CLEAR_MOVE_FUNDS_ERRORS = 'CLEAR_MOVE_FUNDS_ERRORS';
export const MODIFY_CASH_START = 'MODIFY_CASH_START';
export const MODIFY_CASH_SUCCESS = 'MODIFY_CASH_SUCCESS';
export const MODIFY_CASH_ERROR = 'MODIFY_CASH_ERROR';
export const CLEAR_MODIFY_CASH_ERRORS = 'CLEAR_MODIFY_CASH_ERRORS';

export const TRANSFER_TO_OTHERS_ERROR = 'TRANSFER_TO_OTHERS_ERROR ';
export const TRANSFER_TO_OTHERS_START = 'TRANSFER_TO_OTHERS_START ';
export const TRANSFER_TO_OTHERS_SUCCESS =
  'TRANSFER_TO_OTHERS_SUCCESS ';
export const CLEAR_TRANSFER_TO_OTHERS_ERRORS =
  'CLEAR_TRANSFER_TO_OTHERS_ERRORS';
