export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SET_IS_SENDING_CASH = 'SET_IS_SENDING_CASH';
export const SET_IS_SENDING_MONEY = 'SET_IS_SENDING_MONEY';
export const SET_MANAGE_CONTACTS = 'SET_MANAGE_CONTACTS';
