export const UPLOAD_STORE_LOGO_START = 'UPLOAD_STORE_LOGO_START';
export const UPLOAD_STORE_LOGO_SUCCESS = 'UPLOAD_STORE_LOGO_SUCCESS';
export const UPLOAD_STORE_LOGO_ERROR = 'UPLOAD_STORE_LOGO_ERROR';
export const UPLOAD_STORE_LOGO_END = 'UPLOAD_STORE_LOGO_END';
